[build-system]
requires = [
    "setuptools>=61", 
    "wheel",
    "torchreid",
    "torchvision",
    "torch", 
    "numpy",
    "Cython",
    "h5py",
    "Pillow",
    "six",
    "scipy",
    "opencv-python",
    "matplotlib",
    "tb-nightly",
    "future",
    "yacs",
    "gdown",
    "flake8",
    "yapf",
    "isort==4.3.21",
    "imageio",
    "soccernet~=0.1.25"
]
build-backend = "setuptools.build_meta"

[project]
name = "torchreid"
version = "0.0.0"
description = "torchreid package"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]